# Generated by Django 4.2 on 2025-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_game',
            field=models.CharField(blank=True, choices=[('CS2', 'Counter-Strike 2'), ('DOTA2', 'Dota 2'), ('VAL', 'Valorant'), ('LOL', 'League of Legends'), ('COD', 'Call of Duty'), ('OW2', 'Overwatch 2'), ('FIFA', 'FIFA'), ('OTHER', 'Other')], max_length=10, null=True, verbose_name='Любимые игры'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='user',
            name='steam_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Steam профиль'),
        ),
    ]
