# Generated by Django 4.2 on 2025-04-01 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_game_remove_user_favorite_game_user_favorite_games'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название турнира')),
                ('type', models.CharField(choices=[('team', 'Командный'), ('solo', 'Одиночный')], max_length=10, verbose_name='Тип турнира')),
                ('discipline', models.CharField(choices=[('CS2', 'CS 2'), ('DOTA2', 'DOTA 2'), ('LOL', 'League of Legends'), ('VALORANT', 'Valorant')], max_length=20, verbose_name='Дисциплина')),
                ('max_teams', models.PositiveIntegerField(verbose_name='Максимальное количество команд')),
                ('max_team_members', models.PositiveIntegerField(verbose_name='Максимальное количество участников в команде')),
                ('format', models.CharField(choices=[('participants', 'Только участники'), ('group_stage_1', 'Групповой этап 1'), ('group_stage_2', 'Групповой этап 2'), ('playoff', 'Плей-офф')], max_length=30, verbose_name='Формат турнира')),
                ('prize_pool', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Призовой фонд (в $)')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('logo', models.ImageField(blank=True, default='default_team_logo.png', null=True, upload_to='team_logos/', verbose_name='Логотип')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель команды')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='users.tournament', verbose_name='Турнир')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.team', verbose_name='Команда')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь сайта')),
            ],
        ),
    ]
