# Generated by Django 4.2 on 2025-04-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_game_options_tournament_team_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название рамки')),
                ('image', models.ImageField(upload_to='profile_frames/', verbose_name='Изображение рамки')),
                ('price', models.PositiveIntegerField(verbose_name='Цена в очках или валюте')),
            ],
            options={
                'verbose_name': 'Рамка профиля',
                'verbose_name_plural': 'Рамки профиля',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='purchased_frames',
            field=models.ManyToManyField(blank=True, to='users.profileframe', verbose_name='Купленные рамки'),
        ),
        migrations.AddField(
            model_name='user',
            name='selected_frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_frame', to='users.profileframe', verbose_name='Выбранная рамка'),
        ),
    ]
