# Generated by Django 4.2 on 2025-05-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Раунд')),
                ('order_in_round', models.PositiveIntegerField(verbose_name='Порядок в раунде')),
                ('score_team1', models.PositiveIntegerField(default=0, verbose_name='Счёт команды\xa01')),
                ('score_team2', models.PositiveIntegerField(default=0, verbose_name='Счёт команды\xa02')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Матч завершён')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team1', to='users.team', verbose_name='Команда\xa01')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team2', to='users.team', verbose_name='Команда\xa02')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='users.tournament', verbose_name='Турнир')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='users.team', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['round_number', 'order_in_round'],
                'unique_together': {('tournament', 'round_number', 'order_in_round')},
            },
        ),
    ]
