"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i^zl6tox_sqq&j_oa^o*a$v0zz&29d^*=7d01wc)pp!51)y9im'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.User'
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'esports_hub',
        'USER': 'esports_hub_user',
        'PASSWORD': 'esports_hub',
        'HOST': '185.22.67.9',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = "staticfiles"

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
MEDIA_URL = '/uploads/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    # Основное
    "site_title": "ESPORTSHUB",  
    "site_header": "ESPORTSHUB Панель управления",
    "site_brand": "ESPORTSHUB Admin", 
    "site_logo": "/ESPORTSHUB.svg",  # Логотип
    "site_logo_classes": "img-responsive shadow-sm",  # Новые классы оформления
    "site_logo_width": "128px",  # Увеличиваем размер для лучшей видимости
    "site_logo_height": "auto",  # Сохраняем пропорции
    "welcome_sign": "Добро пожаловать в административный раздел ESPORTSHUB",
    "copyright": "ESPORTSHUB",

    # Верхнее меню
    "topmenu_links": [
        {"name": "На сайт", "url": "/", "icon": "fas fa-globe"},  # Переход на сайт
    ],

    # Боковая панель
    "show_sidebar": True,  
    "navigation_expanded": True,  
    "custom_links": {  
        "my_app": [
            {"name": "Статистика", "url": "/admin/my_app/report/", "icon": "fas fa-chart-bar"},
        ]
    },

    # Подключение кастомного CSS для полного контроля
    "custom_css": "admin/custom.css",
    "custom_js": None,

    # Настройки интерфейса
    "ui_tweaks": {
        "theme": "darkly",  # Темная тема
        "dark_mode": True,  # Включение темного режима
        "navbar": "navbar-dark bg-black",  # Верхняя панель - черная
        "sidebar": "sidebar-dark-primary",  # Боковая панель - темная
        "accent": "accent-black",  # Черный акцент
        "navbar_fixed": True,  # Закрепленная верхняя панель
        "sidebar_fixed": True,  # Закрепленная боковая панель
        "body_small_text": True,  # Более мелкий текст
        "footer_small_text": True,
        "layout_boxed": False,
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # Используйте любую тему
    "dark_mode": True,
    "body_small_text": True,
    "navbar": "navbar-dark bg-black",
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-dark",
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
    "layout_boxed": False,
    "footer_small_text": True,
    "dark_mode_theme": "cyborg",
    "accent": "accent-black",
    "button_classes": {
        "primary": "btn-dark",
        "secondary": "btn-outline-light",
    },
}
